inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Layout/LineLength:
  Exclude:
    - lib/humanize/locales/constants/*.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/CollectionLiteralLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/WordArray:
  Exclude:
    - lib/humanize/locales/constants/*.rb
