AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Gemspec/DevelopmentDependencies:
  Enabled: false

Layout/LineLength:
  Max: 200
  Exclude:
    - lib/humanize/locales/constants/*.rb

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/CollectionLiteralLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 10

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/WordArray:
  Exclude:
    - lib/humanize/locales/constants/*.rb

