name: Ruby

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        ruby_version: [3.3, 3.2, 3.1]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: ${{ matrix.ruby_version }}
    - name: Build and test with Rake
      run: |
        bundle exec rspec
        bundle exec rubocop
